CREATE TABLE IF NOT EXISTS suspicious_logs (
    id_log INT AUTO_INCREMENT PRIMARY KEY,
    device_id VARCHAR(100) NOT NULL,
    event_type ENUM('UNKNOWN_FACE', 'SPOOF_ATTEMPT', 'MULTIPLE_FACES', 'LOW_QUALITY', 'OTHER') NOT NULL,
    confidence DECIMAL(5,2) DEFAULT NULL,
    image_path VARCHAR(255) DEFAULT NULL,
    notes TEXT DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
